### ISSUE TITLE
Hello world fails

### ISSUE THREAD

**Issue by rdebath** [hii488/Brainfuck-Interpreter#1]
This BF program should print "Hello World!"

``` bf
>++++++++[-<+++++++++>]<.>[][<-]>+>-[+]++>++>+++[>[->+++<<+++>]<<]>-----.
>->+++..+++.>-.<<+[>[+>+]>>]<--------------.>>.+++.------.--------.>+.>+.
```

**Comment by Elendrial** [comment]
Thanks for pointing this out! I don't know why I didn't test this originally, but it's all fixed now.

**Comment by rdebath** [comment]
Thanks for your last commit, I didn't realise Java was so pedantic about it's 8bit integer type. Both in the way that "byte is an integer so must be signed" and "inline constants must not be wrapped unlike actual calculations". 

So I've added pre-casting to my code when it's using byte cells for the tape in java.
